stages:
  - build
  - deploy

variables:
  BACKEND_IMAGE: docker.io/$DOCKER_USERNAME/nexdesk-backend
  FRONTEND_IMAGE: docker.io/$DOCKER_USERNAME/nexdesk-frontend

build_backend:
  stage: build
  script:
    - echo "Building Backend..."
    - podman build -t $BACKEND_IMAGE:v2 ./backend
    - echo $DOCKER_PASSWORD | podman login docker.io -u $DOCKER_USERNAME --password-stdin
    - podman push $BACKEND_IMAGE:v2

build_frontend:
  stage: build
  script:
    - echo "Building Frontend..."
    - podman build -t $FRONTEND_IMAGE:v3 ./frontend
    - echo $DOCKER_PASSWORD | podman login docker.io -u $DOCKER_USERNAME --password-stdin
    - podman push $FRONTEND_IMAGE:v3

deploy:
  stage: deploy
  script:
    - echo "Logging into OpenShift..."
    - oc login $OPENSHIFT_SERVER --token=$OPENSHIFT_TOKEN --insecure-skip-tls-verify=true

    - oc project $OPENSHIFT_PROJECT

    - echo "Importing latest Backend image..."
    - oc import-image nexdesk-backend:v2 --confirm

    - echo "Importing latest Frontend image..."
    - oc import-image nexdesk-frontend:v3 --confirm

    - echo "Restarting Backend deployment..."
    - oc rollout restart deployment/nexdesk-backend

    - echo "Restarting Frontend deployment..."
    - oc rollout restart deployment/nexdesk-frontend

    - oc rollout status deployment/nexdesk-backend
    - oc rollout status deployment/nexdesk-frontend

only:
  - main